export const weatherFood = {
  hot: {
    food: '망고빙수',
    weatherTxt: '더운',
    temp: 30,
    weatherTxtEN: '',
    tasteTxt: '시원한',
    tasteTxtLong: '달달하고 시원한 망고빙수를',
  },
  cold: {
    food: '칼국수',
    weatherTxt: '추운',
    temp: 0,
    weatherTxtEN: '',
    tasteTxt: '따뜻한',
    tasteTxtLong: '몸도 마음도 따뜻해지는 맛있는 식사를',
  },
  windy: {
    food: '순두부찌개',
    weatherTxt: '쌀쌀한',
    temp: 10,
    weatherTxtEN: '',
    tasteTxt: '얼큰한',
    tasteTxtLong: '몸도 마음도 따뜻해지는 맛있는 식사를',
  },
  sunny: {
    food: '햄버거',
    weatherTxtEN: 'clear sky',
    weatherTxt: '맑은',
    tasteTxt: '맛있는',
    tasteTxtLong: '오늘은 색다른 식사를',
  },
  rain: {
    food: '파전',
    weatherTxtEN: 'rain',
    weatherTxt: '비오는',
    tasteTxt: '맛있는',
    tasteTxtLong: '바삭바삭하고 따듯한 파전을',
  },
  snow: {
    food: '우동',
    weatherTxtEN: 'snow',
    weatherTxt: '눈오는',
    tasteTxt: '따뜻한',
    tasteTxtLong: '몸도 마음도 따뜻해지는 맛있는 식사를',
  },
}
