import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  //const [vongole, setVongole] = useState({});

  const fetchData = async () => {
    const response = await fetch(
      `https://api.edamam.com/search?q=chicken&app_id=${process.env.NEXT_PUBLIC_APP_ID}&app_key=${process.env.NEXT_PUBLIC_APP_KEY}`
    );
    const jsonData = await response.json();
    console.log(jsonData);
    //setVongole(jsonData.hits[3].recipe);
  };

  useEffect(() => {
    fetchData();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <section className={`${styles.mainfirst} first_content`}>
          <div className="layout_size">
            <h2 className={styles.title}>
              HELP YOU FIND BEST <p>FOOD RECIPES</p>
            </h2>
            <div className={styles.search}></div>
          </div>
        </section>
        <section className={`${styles.mainsecond} layout_size`}>
          <div className={styles.infoText}>
            <h3>
              Recipe
              <br /> A lot of food <br /> ingredients
            </h3>
            <div>
              <p>
                It is a long established fact that a reader will be distracted
                by the readable content of a page when looking at its layout.
              </p>
            </div>
          </div>
          <div className={styles.infoList}>
            <div>
              <div className="list_img">
                <Image
                  src={"/image/pasta.avif"}
                  alt="pasta"
                  width={500}
                  height={540}
                />
              </div>
              <div className="list_name">
                <p>PASTA</p>
              </div>
            </div>
            <div>
              <div className="list_img">
                <Image
                  src={"/image/pork.avif"}
                  alt="pork"
                  width={500}
                  height={540}
                />
              </div>
              <div className="list_name">
                <p>PORK</p>
              </div>
            </div>
            <div>
              <div className="list_img">
                <Image
                  src={"/image/egg.avif"}
                  alt="egg"
                  width={500}
                  height={540}
                />
              </div>
              <div className="list_name">
                <p>EGG</p>
              </div>
            </div>
          </div>
        </section>
        <section className={`${styles.mainthird} layout_size`}>
          <div className={styles.infoText}>
            <h3>
              Top Food <br />
              Curator
            </h3>
          </div>
          <div className={styles.rankerList}>
            <div className={styles.topRanker}>
              <div></div>
              <div></div>
            </div>
            <div className={styles.otherRanker}>
              <div>
                <div>
                  <p>Itis along</p>
                </div>
                <div className="ranker_img"></div>
              </div>
              <div>
                <div>
                  {" "}
                  <p>Itis along</p>
                </div>
                <div className="ranker_img"></div>
              </div>
              <div>
                <div>
                  {" "}
                  <p>Itis along</p>
                </div>
                <div className="ranker_img"></div>
              </div>
            </div>
          </div>
        </section>
        <section className={`${styles.mainfourth} layout_size`}>
          <div className={styles.fourthLeft}>
            <p className="fourth_title">
              EXPERIENCE OF <br />
              REAL RECIPES <br />
              TASTE
            </p>
            <div className="fourth_info">
              <div></div>
              <p>
                It is a long established fact that a reader will be distracted
              </p>
              <div>VIEW ALL</div>
            </div>
          </div>
          <div className="recipes_img"></div>
        </section>
        <section className={`${styles.mainfifth} layout_size`}>
          <div>
            <p>Check your nutrition</p>
            <p>
              It is a long established fact that a reader will be distracted by
              the readable content of a page when looking at its layout.
            </p>
          </div>
          <div></div>
        </section>
      </main>
    </>
  );
}
